### ISSUE TITLE
Getting a exception thrown

### ISSUE THREAD

**Issue by anthr76** [theriley106/SneakerBotTutorials#11] opened 2017-12-09 21:33 UTC
AttributeError: 'dict' object has no attribute 'replace'

**Comment by scyzemic** [comment] 2017-12-09 23:59
looks like the issue is [this line](https://github.com/theriley106/SneakerBotTutorials/blob/master/main.py#L63) in main.py for the case where `proxy = None`, this is my first time looking at python, so I'm not sure how to go about a fix for a PR

**Comment by scyzemic** [comment] 2017-12-11 01:08
Looks like this was fixed on last change pushed to master

**Comment by theriley106** [comment] 2017-12-15 05:34
@anthr76 Sorry about that.  I pushed a change without testing it fully.  Should be fixed now.

**Closed as completed by theriley106** 2017-12-15 05:34 UTC
